using System.Security.Cryptography;
using System.Text;
using EngineIQ.Domain.Indexing;
using EngineIQ.Domain.Interfaces;

namespace EngineIQ.ContextBuilder.Indexing;

/// <summary>Roslyn-based chunking for C#; sliding-window for known text extensions; empty otherwise.</summary>
public sealed class CompositeCodeChunker : ICodeChunker
{
    private static readonly HashSet<string> WindowExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".ts", ".tsx", ".html", ".scss", ".css", ".js", ".jsx", ".json", ".yaml", ".yml",
        ".sql", ".md", ".csproj", ".sln", ".py", ".go", ".dart", ".razor", ".cshtml"
    };

    private readonly RoslynCSharpChunker _roslyn = new();
    private readonly SlidingWindowChunker _slidingWindow = new();

    public Task<IReadOnlyList<CodeChunkCandidate>> ChunkAsync(
        string filePath,
        string content,
        CancellationToken cancellationToken = default)
    {
        if (IsGeneratedPath(filePath) || ContainsAutoGeneratedMarker(content))
            return Task.FromResult<IReadOnlyList<CodeChunkCandidate>>(Array.Empty<CodeChunkCandidate>());

        var extension = Path.GetExtension(filePath);
        IReadOnlyList<RawChunk> raw;
        if (extension.Equals(".cs", StringComparison.OrdinalIgnoreCase))
            raw = _roslyn.Chunk(filePath, content) ?? PrefixedWindow(filePath, content);
        else if (WindowExtensions.Contains(extension))
            raw = PrefixedWindow(filePath, content);
        else
            return Task.FromResult<IReadOnlyList<CodeChunkCandidate>>(Array.Empty<CodeChunkCandidate>());

        var candidates = new List<CodeChunkCandidate>(raw.Count);
        for (var i = 0; i < raw.Count; i++)
        {
            var r = raw[i];
            candidates.Add(new CodeChunkCandidate(
                filePath,
                i,
                r.Content,
                r.StartLine,
                r.EndLine,
                ComputeSha256Hex(r.Content),
                r.SymbolName,
                r.Kind));
        }

        return Task.FromResult<IReadOnlyList<CodeChunkCandidate>>(candidates);
    }

    private IReadOnlyList<RawChunk> PrefixedWindow(string filePath, string content)
    {
        var windows = _slidingWindow.Chunk(content);
        if (windows.Count == 0)
            return windows;

        return windows
            .Select(w => w with
            {
                Content = $"// file: {filePath} lines {w.StartLine}-{w.EndLine}\n{w.Content}"
            })
            .ToList();
    }

    private static bool IsGeneratedPath(string filePath)
    {
        var name = Path.GetFileName(filePath);
        return name.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase)
               || name.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
               || name.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool ContainsAutoGeneratedMarker(string content)
    {
        var probe = content.Length <= 2048 ? content : content[..2048];
        return probe.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
    }

    private static string ComputeSha256Hex(string content) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content))).ToLowerInvariant();
}
