using EngineIQ.ContextBuilder.Indexing;

namespace EngineIQ.Tests.Unit;

public class CodeChunkerTests
{
    [Fact]
    public async Task CompositeCodeChunker_chunks_csharp_file_per_member()
    {
        const string source = """
            namespace Sample;

            public class Calculator
            {
                public int Add(int a, int b)
                {
                    return a + b;
                }

                public int Subtract(int a, int b)
                {
                    return a - b;
                }

                public int Multiply(int a, int b)
                {
                    return a * b;
                }
            }
            """;

        var chunker = new CompositeCodeChunker();
        var chunks = await chunker.ChunkAsync("Sample/Calculator.cs", source);

        Assert.Equal(3, chunks.Count);
        Assert.Contains(chunks, c => c.SymbolName == "Sample.Calculator.Add" && c.Kind == "method");
        Assert.Contains(chunks, c => c.SymbolName == "Sample.Calculator.Subtract" && c.Kind == "method");
        Assert.Contains(chunks, c => c.SymbolName == "Sample.Calculator.Multiply" && c.Kind == "method");
        Assert.All(chunks, c => Assert.Contains("// Sample.Calculator", c.Content));
        Assert.All(chunks, c => Assert.Equal(64, c.ContentSha256.Length));
    }

    [Fact]
    public async Task CompositeCodeChunker_dto_record_is_single_type_chunk()
    {
        const string source = """
            namespace Sample;

            public record InvoiceDto(string Id, decimal Amount);
            """;

        var chunker = new CompositeCodeChunker();
        var chunks = await chunker.ChunkAsync("InvoiceDto.cs", source);

        Assert.Single(chunks);
        Assert.Equal("Sample.InvoiceDto", chunks[0].SymbolName);
        Assert.Equal("type", chunks[0].Kind);
    }

    [Fact]
    public async Task CompositeCodeChunker_skips_generated_files()
    {
        const string source = """
            namespace Sample;
            public class Generated { public void M() { var x = 1; } }
            """;

        var chunker = new CompositeCodeChunker();
        Assert.Empty(await chunker.ChunkAsync("Form1.Designer.cs", source));
        Assert.Empty(await chunker.ChunkAsync("Foo.g.cs", source));
        Assert.Empty(await chunker.ChunkAsync("Hand.cs", "// <auto-generated>\n" + source));
    }

    [Fact]
    public async Task CompositeCodeChunker_malformed_csharp_falls_back_to_window()
    {
        // Unbalanced braces still parse into a tree; use a non-type file body that Roslyn finds no types for.
        var lines = Enumerable.Range(1, 20).Select(i => $"line {i} without types");
        var content = string.Join('\n', lines);

        var chunker = new CompositeCodeChunker();
        // .cs with no type declarations → Roslyn returns null → window fallback
        var chunks = await chunker.ChunkAsync("Notes.cs", content);
        Assert.NotEmpty(chunks);
        Assert.All(chunks, c => Assert.StartsWith("// file: Notes.cs", c.Content));
    }

    [Fact]
    public async Task CompositeCodeChunker_same_content_produces_same_hash()
    {
        const string source = """
            namespace Sample;
            public class A
            {
                public void M()
                {
                    var x = 1;
                }
            }
            """;
        var chunker = new CompositeCodeChunker();

        var first = await chunker.ChunkAsync("A.cs", source);
        var second = await chunker.ChunkAsync("A.cs", source);

        Assert.Equal(first.Select(c => c.ContentSha256), second.Select(c => c.ContentSha256));
    }

    [Fact]
    public async Task CompositeCodeChunker_falls_back_to_sliding_window_for_non_csharp()
    {
        var lines = Enumerable.Range(1, 120).Select(i => $"line {i}");
        var content = string.Join('\n', lines);

        var chunker = new CompositeCodeChunker();
        var chunks = await chunker.ChunkAsync("README.md", content);

        Assert.NotEmpty(chunks);
        Assert.All(chunks, c => Assert.Null(c.SymbolName));
        Assert.All(chunks, c => Assert.StartsWith("// file: README.md", c.Content));
    }

    [Fact]
    public async Task CompositeCodeChunker_unknown_extension_returns_empty()
    {
        var chunker = new CompositeCodeChunker();
        Assert.Empty(await chunker.ChunkAsync("photo.png", "not text"));
    }

    [Fact]
    public void SlidingWindowChunker_splits_large_file_into_overlapping_windows()
    {
        var lines = Enumerable.Range(1, 200).Select(i => $"line {i}");
        var content = string.Join('\n', lines);

        var chunker = new SlidingWindowChunker();
        var chunks = chunker.Chunk(content);

        Assert.True(chunks.Count > 1);
        Assert.Equal(1, chunks[0].StartLine);
        Assert.Equal(60, chunks[0].EndLine);
        // Step = window(60) - overlap(15) = 45 lines between window starts.
        Assert.Equal(46, chunks[1].StartLine);
    }

    [Fact]
    public void SlidingWindowChunker_skips_windows_with_too_few_non_empty_lines()
    {
        var content = string.Join('\n', Enumerable.Repeat("", 60));

        var chunker = new SlidingWindowChunker();
        var chunks = chunker.Chunk(content);

        Assert.Empty(chunks);
    }

    [Fact]
    public void SlidingWindowChunker_sub_five_line_file_returns_empty()
    {
        var content = "a\nb\nc\nd";
        Assert.Empty(new SlidingWindowChunker().Chunk(content));
    }

    [Fact]
    public void SlidingWindowChunker_returns_empty_for_empty_content()
    {
        var chunker = new SlidingWindowChunker();
        Assert.Empty(chunker.Chunk(string.Empty));
    }
}
